### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by trmdi**
Add openSUSE Tumbleweed

### CODE REVIEW

**Comment by zzag** [comment]
Thanks. Just one thing, could you please put it under a new heading, e.g.

```md
### Installation

#### openSUSE Tumbleweed

...

#### Build from source

...
```

**Comment by trmdi** [comment]
Updated !

**Comment by zzag** [comment]
Last nitpick: could you please move binary packages section before building from source section (usually it's the last resort).

**Comment by zzag** [comment]
Thanks.

**Pull request merged**
