### PR TITLE
Add dbus devel deps

### PR DESCRIPTION
**Pull request by marcdeop**
Even though #2 is marked as resolved, I faced the issue while compiling on Fedora.

This will:
* Discovers `org.kde.kwin.Effects.xml ` properly.
* Remove reference in README.md to install libdbus-1-dev (not needed anymore)

### CODE REVIEW

**Comment by marcdeop** [comment]
I assumed `Finddbus.cmake` is usable as it's distributed under BSD license.

**Comment by zzag** [comment]
Currently, this plugin uses pkg-config to determine the file path of `org.kde.kwin.Effects.xml`

https://github.com/zzag/kwin-effects-yet-another-magic-lamp/blob/f411876086099638677d35c4cc023e5d046eff6a/src/kcm/CMakeLists.txt#L10-L12

but it is sort of incorrect because KWin ships a config file.

We need to do something along these lines instead

```cmake
# src/CMakeLists.txt
find_package(KWinDBusInterface CONFIG REQUIRED)

# src/kcm/CMakeLists.txt
qt5_add_dbus_interface (kcm_SRCS ${KWIN_EFFECTS_INTERFACE} kwineffects_interface) 
```

**Comment by marcdeop** [comment]
@zzag but that sounds like a separate issue.

Should I open a bug report and try to fix it there?

**Comment by zzag** [comment]
This effect needs dbus-devel only because of the interfaces_dir variable, but as I said previously, there is a better way to find the file path of org.kde.kwin.Effects.xml, which doesn't require installing dbus-1-dev or dbus-devel.

**Comment by marcdeop** [comment]
> This effect needs dbus-devel only because of the interfaces_dir variable, but as I said previously, there is a better way to find the file path of org.kde.kwin.Effects.xml, which doesn't require installing dbus-1-dev or dbus-devel.

ok, now I get it :-)

**Comment by marcdeop** [comment]
@zzag I updated the PR, feel free to re-review again :-)

**Comment by zzag** [comment]
Thanks.

**Pull request merged**
